"""add_performance_indexes

Revision ID: 13a6bc7f71e3
Revises: 8ad084091aa8
Create Date: 2025-11-01 06:49:10.796930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a6bc7f71e3'
down_revision = '8ad084091aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('contract')
    op.drop_table('customer_complaints')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('time_in')
        batch_op.drop_column('time_out')
        batch_op.drop_column('location')
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('client_support', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_client_support_created_by_user', 'user', ['created_by'], ['id'])
        batch_op.create_foreign_key('fk_client_support_last_transferred_by_user', 'user', ['last_transferred_by'], ['id'])
        batch_op.create_foreign_key('fk_client_support_assigned_to_user', 'user', ['assigned_to'], ['id'])

    with op.batch_alter_table('employee_presence', schema=None) as batch_op:
        batch_op.drop_column('is_online')

    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.drop_column('reason')

    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('housing_allowance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('transport_allowance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('food_allowance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phone_allowance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('other_allowances', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('commission', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('overtime_hours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('overtime_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('incentives', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('absence_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('absence_deduction', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('late_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('late_deduction', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('loan_deduction', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('other_deductions', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('health_insurance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gross_salary', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_deductions', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reference_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('paid_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_final', sa.Boolean(), nullable=True))

    with op.batch_alter_table('performance', schema=None) as batch_op:
        batch_op.drop_column('comments')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name_ar', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('company_name_en', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('company_logo', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('company_email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('company_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('company_address_ar', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('company_address_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('company_website', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tax_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('commercial_register', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('allowed_radius_meters', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('break_start', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('break_end', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('work_days', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('weekend_days', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('late_arrival_threshold_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('early_leave_threshold_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('auto_checkout_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('auto_checkout_time', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('require_checkout_location', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('annual_leave_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sick_leave_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('casual_leave_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('carry_forward_leaves', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('max_carry_forward_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('leave_approval_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('min_leave_notice_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payroll_currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('payroll_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('overtime_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weekend_overtime_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('holiday_overtime_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('auto_calculate_overtime', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deduct_late_from_salary', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('late_deduction_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('email_notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sms_notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_on_late_arrival', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_on_absence', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_on_leave_request', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_managers_on_employee_actions', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('password_min_length', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('password_expiry_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('session_timeout_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('require_password_change_first_login', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('date_format', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('time_format', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fiscal_year_start_month', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('records_per_page', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('auto_backup_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('backup_frequency_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_backup_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('report_logo_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('report_footer_text_ar', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('report_footer_text_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('performance_review_frequency_months', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('min_performance_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_performance_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('auto_generate_performance_alerts', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.Integer(), nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('value')

    with op.batch_alter_table('whatsapp_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('message_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('audio_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('document_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('caption', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('message_type',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('message_content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('direction',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_whatsapp_messages_conversation_id', 'whatsapp_conversations', ['conversation_id'], ['id'])
        batch_op.drop_column('message_date')
        batch_op.drop_column('complaint_id')
        batch_op.drop_column('sent_by')
        batch_op.drop_column('customer_phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_phone', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('sent_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('complaint_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('message_date', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint('fk_whatsapp_messages_conversation_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customer_complaints', ['complaint_id'], ['id'])
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)
        batch_op.alter_column('direction',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
        batch_op.alter_column('message_content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('message_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=8),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('caption')
        batch_op.drop_column('video_url')
        batch_op.drop_column('document_url')
        batch_op.drop_column('image_url')
        batch_op.drop_column('audio_url')
        batch_op.drop_column('message_id')
        batch_op.drop_column('conversation_id')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('updated_by')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('auto_generate_performance_alerts')
        batch_op.drop_column('max_performance_score')
        batch_op.drop_column('min_performance_score')
        batch_op.drop_column('performance_review_frequency_months')
        batch_op.drop_column('report_footer_text_en')
        batch_op.drop_column('report_footer_text_ar')
        batch_op.drop_column('report_logo_enabled')
        batch_op.drop_column('last_backup_date')
        batch_op.drop_column('backup_frequency_days')
        batch_op.drop_column('auto_backup_enabled')
        batch_op.drop_column('records_per_page')
        batch_op.drop_column('fiscal_year_start_month')
        batch_op.drop_column('time_format')
        batch_op.drop_column('date_format')
        batch_op.drop_column('timezone')
        batch_op.drop_column('language')
        batch_op.drop_column('two_factor_enabled')
        batch_op.drop_column('require_password_change_first_login')
        batch_op.drop_column('session_timeout_minutes')
        batch_op.drop_column('max_login_attempts')
        batch_op.drop_column('password_expiry_days')
        batch_op.drop_column('password_min_length')
        batch_op.drop_column('notify_managers_on_employee_actions')
        batch_op.drop_column('notify_on_leave_request')
        batch_op.drop_column('notify_on_absence')
        batch_op.drop_column('notify_on_late_arrival')
        batch_op.drop_column('whatsapp_notifications_enabled')
        batch_op.drop_column('sms_notifications_enabled')
        batch_op.drop_column('email_notifications_enabled')
        batch_op.drop_column('late_deduction_rate')
        batch_op.drop_column('deduct_late_from_salary')
        batch_op.drop_column('auto_calculate_overtime')
        batch_op.drop_column('holiday_overtime_rate')
        batch_op.drop_column('weekend_overtime_rate')
        batch_op.drop_column('overtime_rate')
        batch_op.drop_column('payroll_day')
        batch_op.drop_column('payroll_currency')
        batch_op.drop_column('min_leave_notice_days')
        batch_op.drop_column('leave_approval_required')
        batch_op.drop_column('max_carry_forward_days')
        batch_op.drop_column('carry_forward_leaves')
        batch_op.drop_column('casual_leave_days')
        batch_op.drop_column('sick_leave_days')
        batch_op.drop_column('annual_leave_days')
        batch_op.drop_column('require_checkout_location')
        batch_op.drop_column('auto_checkout_time')
        batch_op.drop_column('auto_checkout_enabled')
        batch_op.drop_column('early_leave_threshold_min')
        batch_op.drop_column('late_arrival_threshold_min')
        batch_op.drop_column('weekend_days')
        batch_op.drop_column('work_days')
        batch_op.drop_column('break_end')
        batch_op.drop_column('break_start')
        batch_op.drop_column('allowed_radius_meters')
        batch_op.drop_column('commercial_register')
        batch_op.drop_column('tax_number')
        batch_op.drop_column('company_website')
        batch_op.drop_column('company_address_en')
        batch_op.drop_column('company_address_ar')
        batch_op.drop_column('company_phone')
        batch_op.drop_column('company_email')
        batch_op.drop_column('company_logo')
        batch_op.drop_column('company_name_en')
        batch_op.drop_column('company_name_ar')

    with op.batch_alter_table('performance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.TEXT(), nullable=True))

    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_column('is_final')
        batch_op.drop_column('notes')
        batch_op.drop_column('paid_at')
        batch_op.drop_column('paid_by')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('reference_number')
        batch_op.drop_column('account_number')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('total_deductions')
        batch_op.drop_column('gross_salary')
        batch_op.drop_column('health_insurance')
        batch_op.drop_column('other_deductions')
        batch_op.drop_column('loan_deduction')
        batch_op.drop_column('late_deduction')
        batch_op.drop_column('late_minutes')
        batch_op.drop_column('absence_deduction')
        batch_op.drop_column('absence_days')
        batch_op.drop_column('incentives')
        batch_op.drop_column('overtime_amount')
        batch_op.drop_column('overtime_hours')
        batch_op.drop_column('commission')
        batch_op.drop_column('other_allowances')
        batch_op.drop_column('phone_allowance')
        batch_op.drop_column('food_allowance')
        batch_op.drop_column('transport_allowance')
        batch_op.drop_column('housing_allowance')
        batch_op.drop_column('year')
        batch_op.drop_column('month')

    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.TEXT(), nullable=True))

    with op.batch_alter_table('employee_presence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_online', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('client_support', schema=None) as batch_op:
        batch_op.drop_constraint('fk_client_support_created_by_user', type_='foreignkey')
        batch_op.drop_constraint('fk_client_support_last_transferred_by_user', type_='foreignkey')
        batch_op.drop_constraint('fk_client_support_assigned_to_user', type_='foreignkey')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('time_out', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('time_in', sa.TIME(), nullable=True))

    op.create_table('customer_complaints',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('issue_description', sa.TEXT(), nullable=False),
    sa.Column('issue_date', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), nullable=True),
    sa.Column('assigned_to', sa.INTEGER(), nullable=True),
    sa.Column('referred_to_department', sa.VARCHAR(length=100), nullable=True),
    sa.Column('management_response', sa.TEXT(), nullable=True),
    sa.Column('response_date', sa.DATETIME(), nullable=True),
    sa.Column('resolution_notes', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), server_default=sa.text('("medium")'), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('referred_to_manager', sa.INTEGER(), nullable=True),
    sa.Column('manager_solution', sa.TEXT(), nullable=True),
    sa.Column('manager_response_date', sa.DATETIME(), nullable=True),
    sa.Column('manager_instructions', sa.TEXT(), nullable=True),
    sa.Column('employee_action', sa.TEXT(), nullable=True),
    sa.Column('customer_contact_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('customer_response', sa.TEXT(), nullable=True),
    sa.Column('resolution_details', sa.TEXT(), nullable=True),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('contract_type', sa.VARCHAR(length=32), nullable=True),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('report_type', sa.VARCHAR(length=32), nullable=True),
    sa.Column('generated_at', sa.DATETIME(), nullable=True),
    sa.Column('data', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
