"""Recreate initial migration

Revision ID: 50276ed01927
Revises: 
Create Date: 2025-11-01 01:36:52.740426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50276ed01927'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop temporary table if it exists
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_attendance")

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('timestamp')
        batch_op.drop_column('location')

    # Ensure no NULL values in password_hash before altering the table
    op.execute("UPDATE employee SET password_hash = '' WHERE password_hash IS NULL")

    with op.batch_alter_table('employee', schema=None) as batch_op:
        # Set default value for username where it is NULL
        op.execute("""
            UPDATE employee
            SET username = 'default_username_' || id
            WHERE username IS NULL
        """)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.create_unique_constraint('uq_employee_username', ['username'])

    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=32), nullable=True))

    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        batch_op.drop_column('employee_id')

    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_column('payment_method')
        batch_op.drop_column('payment_date')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint('uq_employee_username', type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
