"""add_indexes_for_performance

Revision ID: 68b38bd7c00d
Revises: 8ad084091aa8
Create Date: 2025-11-01 06:51:00.002999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b38bd7c00d'
down_revision = '22049112290a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_support', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_support_assigned_to_user_id'), ['assigned_to_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_support_status'), ['status'], unique=False)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_job_title'), ['job_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_phone'), ['phone'], unique=False)

    with op.batch_alter_table('employee_presence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_presence_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_presence_employee_id'), ['employee_id'], unique=False)

    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_status'), ['status'], unique=False)

    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_year'), ['year'], unique=False)

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permission_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_permission_module'), ['module'], unique=False)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_name'), ['name'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_name'))

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_module'))
        batch_op.drop_index(batch_op.f('ix_permission_action'))

    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_year'))
        batch_op.drop_index(batch_op.f('ix_payroll_month'))
        batch_op.drop_index(batch_op.f('ix_payroll_employee_id'))

    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_status'))
        batch_op.drop_index(batch_op.f('ix_leave_employee_id'))

    with op.batch_alter_table('employee_presence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_presence_employee_id'))
        batch_op.drop_index(batch_op.f('ix_employee_presence_date'))

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_phone'))
        batch_op.drop_index(batch_op.f('ix_employee_name'))
        batch_op.drop_index(batch_op.f('ix_employee_job_title'))
        batch_op.drop_index(batch_op.f('ix_employee_email'))

    with op.batch_alter_table('client_support', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_support_status'))
        batch_op.drop_index(batch_op.f('ix_client_support_assigned_to_user_id'))

    # ### end Alembic commands ###
